### ISSUE TITLE
Question Category database error

### ISSUE THREAD

**Issue by marcusgreen** [frankkoch/moodle-qbehaviour_studentquiz#1]
I am getting the following error when I go into an instance of StudentQuiz. 
Error: mdb->get_record() found more than one record!

    line 1539 of /lib/dml/moodle_database.php: call to debugging()
    line 1499 of /lib/dml/moodle_database.php: call to moodle_database->get_record_sql()
    line 1478 of /lib/dml/moodle_database.php: call to moodle_database->get_record_select()
    line 92 of /mod/studentquiz/viewlib.php: call to moodle_database->get_record()
    line 87 of /mod/studentquiz/viewlib.php: call to studentquiz_view->check_question_category()
    line 37 of /mod/studentquiz/view.php: call to studentquiz_view->__construct()

I think it was triggered by importing an xml file that contained categories and it seems that this plugin uses tags for organising questions. When I re-imported without categories it was OK. It might be an idea to have some defensive code that deals with the situation where categories are present.

**Comment by frankkoch** [comment]
We will try to implement defensive code in the next version. For the time being: 
- If you go via the Moodle questionbank to export questions created by Studentquiz you should deactivate "Write category to file" and "Write context to file". 
- If you go via Studentquiz to export questions created by Studentquiz these options are not available to prevent confusion.
