### ISSUE TITLE
freezing 3.3.and 3.4 courses

### ISSUE THREAD

**Issue by reactor0138** [frankkoch/moodle-qbehaviour_studentquiz#7]
Hi Frank
as suspected with moodle 3.3 and 3.4 the student quiz is blowing up courses as it tries to load 999 topics to the screen. Plus with no setting in the course settings to reduce the number to something sensible the course just freezes. this is a major bug. You will need to redesign or remove the function of it creating the student compelted quizzes in the 999 section. Please put a warning on your plugin site in moodle. We are busy with roll over for next year and do not have time to fix this ourselves

**Comment by frankkoch** [comment]
Hi Scott
Under Moodle >=3.3, when you add a StudentQuiz activity named "xyz", the hidden section "xyz quizzes" becomes created which stores all the genereated quizzes. Under <3.3 this was the section 999. So far this is ok, however, backup & restore as well as import causes the many empty sections to show up.
I agree that this is a bug under >=3.3 and we are working on this. The idea is that we omit section 999 completely. A solution will be provided in a few weeks. I will place a warning on the plugin page for the time being.
Frank

**Comment by frankkoch** [comment]
Hi Scott, I close this issue now since it is solved with StudentQuiz version 3.0
